version: "3"


tasks:
  local:
    aliases:
      - loc
    cmd: go run cmd/main.go --config=./config/local.yaml

  development:
    aliases:
      - dev
    cmd: go run cmd/main.go --config=./config/dev.yaml

  docker-image:
    aliases:
      - doc-img
    cmd: docker build -t arumandesu/ucms-file-storage-service -t arumandesu/ucms-file-storage-service:0.0.1 . && docker push arumandesu/ucms-file-storage-service -a